export default {
    getHomeData:()=>{
        return {
            code:200,
            data:{
                big_sort:[
                    {
                        name:"美食",
                        icon:"icon-meishi"
                    },
                    {
                        name:"甜点饮品",
                        icon:"icon-cake"
                    },
                    {
                        name:"超市便利",
                        icon:"icon-baihuochaoshi"
                    },
                    {
                        name:"生鲜果蔬",
                        icon:"icon-xinxianguoshu_xinxianshuiguojuzi"
                    },
                    {
                        name:"买药",
                        icon:"icon-yaodian"
                    },
                ],
                small_sort:[
                    {
                        name:"午餐",
                        icon:"icon-wucan"
                    },
                    {
                        name:"蔬菜",
                        icon:"icon-shucai"
                    },
                    {
                        name:"麻辣烫",
                        icon:"icon-malatang"
                    },
                    {
                        name:"小吃",
                        icon:"icon-xiaochi"
                    },
                    {
                        name:"简餐",
                        icon:"icon-jiancan"
                    },
                    {
                        name:"鲜花",
                        icon:"icon-xianhua"
                    },
                    {
                        name:"跑腿",
                        icon:"icon-paotuiAPP"
                    },
                    {
                        name:"龙虾",
                        icon:"icon-longxia"
                    },
                    {
                        name:"夜宵",
                        icon:"icon-yexiao"
                    },
                    {
                        name:"日韩料理",
                        icon:"icon-rihanliaoli"
                    },
                ],
                cententnav_list:[  
                {
                    tab:"天天神券",
                    data:[
                        {
                            pic:"https://www.1616n.com/upload/resources/image/2017/09/26/680843.png",
                            title:"酸菜鱼",
                            sales:3000,
                            price:45,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"http://i0.sinaimg.cn/travel/2013/1114/U6986P704DT20131114113319.jpg",
                            title:"鱼香肉丝",
                            sales:2000,
                            price:25,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"https://imgnews.gmw.cn/attachement/jpg/site2/20160125/7434562759390282227.jpg",
                            title:"回锅肉",
                            sales:2888,
                            price:25,
                            lable:["门店上新","很下饭"],
                        },
                    ],
                },
                {
                    tab:"点评高分",
                    data:[
                        {
                            pic:"http://p3.itc.cn/images01/20201109/069492c3e5cb41eeb682590e0c43b5fd.jpeg",
                            title:"好利蛋糕",
                            sales:5700,
                            price:88,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"http://img.mp.itc.cn/upload/20170204/d6d96912a9744dfdad6dfee403398709_th.jpg",
                            title:"麦当劳麦乐送",
                            sales:3500,
                            price:55,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"http://5b0988e595225.cdn.sohucs.com/images/20181225/d9660a96d29b47e3a801920fa0d9320d.jpeg",
                            title:"重庆鸡公煲",
                            sales:8000,
                            price:35,
                            lable:["门店上新","很下饭"],
                        },
                    ],
                },
                {
                    tab:"会员减满",
                    data:[
                        {
                            pic:"http://s3img.city.sina.com.cn/xiancheng/common/thumbnail/0/b2f46fecf83a85d99797e9ecd5d3c03f.jpg",
                            title:"三米粥",
                            sales:2388,
                            price:10,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"https://i01piccdn.sogoucdn.com/dc3c66b593d3f87d",
                            title:"三只熊披萨",
                            sales:1688,
                            price:25,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"https://i01piccdn.sogoucdn.com/f90680f0e3973700",
                            title:"北京卤肉卷",
                            sales:5588,
                            price:40,
                            lable:["门店上新","很下饭"],
                        },
                    ],
                },  
                {
                    tab:"减配送费",
                    data:[
                        {
                            pic:"http://img.mp.sohu.com/q_mini,c_zoom,w_640/upload/20170703/8b7fd06bf5ce4f1396df3a9a58d9ea8e_th.jpg",
                            title:"北京烤鸭",
                            sales:3888,
                            price:45,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"https://p8.itc.cn/q_70/images03/20210224/8dd276240dba4cc598837f3510ef766f.jpeg",
                            title:"柳州螺蛳粉",
                            sales:7988,
                            price:15,
                            lable:["门店上新","很下饭"],
                        },
                        {
                            pic:"http://5b0988e595225.cdn.sohucs.com/images/20171026/8d543ba8b3b14f3f898a653f7f6b471d.jpeg",
                            title:"芭夯兔",
                            sales:1588,
                            price:98,
                            lable:["门店上新","很下饭"],
                        },
                    ],
                }   
             ]
            }
        }
    }
}